import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpRight, CalendarDays, Camera, Check, ChevronRight, CircleUserRound, CloudSun, Compass, Heart, Plus, Search, Shirt, Sparkles, SunMedium, UserRound, WashingMachine, X } from 'lucide-react'

const images = { hero: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85', blazer: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=85', jeans: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=85', dress: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=600&q=85', shoes: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=600&q=85', bag: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=85', trench: 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=85' }
const initialItems = [
  { id: 1, name: 'Blazer croisé noir', category: 'Hauts', style: 'Chic', image: images.blazer, favorite: true }, { id: 2, name: 'Jean wide leg brut', category: 'Bas', style: 'Casual', image: images.jeans, favorite: true }, { id: 3, name: 'Robe en soie champagne', category: 'Robes', style: 'Soirée', image: images.dress, favorite: false }, { id: 4, name: 'Baskets leather clean', category: 'Chaussures', style: 'Casual', image: images.shoes, favorite: true }, { id: 5, name: 'Sac cuir structuré', category: 'Accessoires', style: 'Chic', image: images.bag, favorite: true }, { id: 6, name: 'Trench coat beige', category: 'Manteaux', style: 'Élégant', image: images.trench, favorite: false },
]
const looks = [
  { id: 1, title: 'Power dressing minimal', note: 'Pour vos rendez-vous de la journée', image: 'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?auto=format&fit=crop&w=900&q=85', tag: 'Recommandation du jour' }, { id: 2, title: 'Urban chic dimanche', note: 'Une allure facile, sans effort', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=700&q=85', tag: 'Casual' }, { id: 3, title: 'Gala & vernissage', note: 'Le soir, avec une pointe de lumière', image: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=700&q=85', tag: 'Soirée' },
]
const hairstyles = [
  { id: 1, title: 'Chignon bas lissé', note: 'Élégant, net et parfait pour le bureau', image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=700&q=85', tag: 'Chic' }, { id: 2, title: 'Wavy naturel', note: 'Le mouvement facile du week-end', image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=700&q=85', tag: 'Casual' }, { id: 3, title: 'Queue basse ruban', note: 'Une finition graphique et féminine', image: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?auto=format&fit=crop&w=700&q=85', tag: 'Soirée' },
]
const navigation = [{ id: 'home', label: 'Accueil', icon: Sparkles }, { id: 'wardrobe', label: 'Mon dressing', icon: Shirt }, { id: 'laundry', label: 'Au lavage', icon: WashingMachine }, { id: 'studio', label: 'Essayage 3D', icon: Camera }, { id: 'hairstyles', label: 'Coiffures', icon: UserRound }, { id: 'favorites', label: 'Tenues favorites', icon: Heart }, { id: 'discover', label: 'Inspirations', icon: Compass }, { id: 'calendar', label: 'Planning', icon: CalendarDays }]

function AddItemModal({ onClose, onAdd }) {
  const [name, setName] = useState(''); const [category, setCategory] = useState('Hauts'); const [photo, setPhoto] = useState(''); const [cameraActive, setCameraActive] = useState(false); const videoRef = useRef(null); const streamRef = useRef(null); const fileRef = useRef(null)
  useEffect(() => () => streamRef.current?.getTracks().forEach((track) => track.stop()), [])
  async function startCamera() { if (!navigator.mediaDevices?.getUserMedia) return; try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' }, audio: false }); streamRef.current = stream; setCameraActive(true); if (videoRef.current) videoRef.current.srcObject = stream } catch { setCameraActive(false) } }
  function capturePhoto() { const video = videoRef.current; if (!video?.videoWidth) return; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d').drawImage(video, 0, 0); setPhoto(canvas.toDataURL('image/jpeg', 0.86)); streamRef.current?.getTracks().forEach((track) => track.stop()); setCameraActive(false) }
  function readFile(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(reader.result); reader.readAsDataURL(file) }
  function submit(event) { event.preventDefault(); if (name.trim() && photo) onAdd({ name: name.trim(), category, image: photo }) }
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal camera-modal" onMouseDown={(event) => event.stopPropagation()}><button className="icon-button modal-close" onClick={onClose} aria-label="Fermer"><X size={18} /></button><span className="eyebrow">Nouvelle pièce</span><h2>Photographier votre pièce</h2><p className="modal-copy">Une photo nette aide AL Studio à mieux composer vos silhouettes.</p><div className="camera-preview">{cameraActive ? <video ref={videoRef} autoPlay playsInline /> : photo ? <img src={photo} alt="Aperçu de la pièce" /> : <div className="camera-placeholder"><Camera size={25} /><span>Votre photo apparaîtra ici</span></div>}</div><div className="camera-actions"><button className="secondary-button" type="button" onClick={startCamera}><Camera size={16} /> Activer la caméra</button>{cameraActive && <button className="primary-button" type="button" onClick={capturePhoto}><Check size={16} /> Prendre la photo</button>}<button className="text-button" type="button" onClick={() => fileRef.current?.click()}>Importer une image</button><input ref={fileRef} className="hidden-input" type="file" accept="image/*" onChange={readFile} /></div><form onSubmit={submit}><label>Nom de la pièce<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex. Chemise en lin blanc" /></label><label>Catégorie<select value={category} onChange={(event) => setCategory(event.target.value)}><option>Hauts</option><option>Bas</option><option>Robes</option><option>Manteaux</option><option>Chaussures</option><option>Accessoires</option></select></label><button className="primary-button full-width" disabled={!photo || !name.trim()} type="submit"><Plus size={17} /> Ajouter au dressing</button></form></div></div>
}

function BodyScan({ onClose, onComplete }) {
  const [active, setActive] = useState(false); const [photo, setPhoto] = useState(''); const videoRef = useRef(null); const streamRef = useRef(null)
  useEffect(() => () => streamRef.current?.getTracks().forEach((track) => track.stop()), [])
  async function startScan() { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'user' }, audio: false }); streamRef.current = stream; setActive(true); if (videoRef.current) videoRef.current.srcObject = stream } catch { setActive(false) } }
  function capture() { const video = videoRef.current; if (!video?.videoWidth) return; const canvas = document.createElement('canvas'); canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext('2d').drawImage(video, 0, 0); setPhoto(canvas.toDataURL('image/jpeg', 0.85)); streamRef.current?.getTracks().forEach((track) => track.stop()); setActive(false) }
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal scan-modal" onMouseDown={(event) => event.stopPropagation()}><button className="icon-button modal-close" onClick={onClose} aria-label="Fermer"><X size={18} /></button><span className="eyebrow">Studio 3D</span><h2>Scanner votre silhouette</h2><p className="modal-copy">Placez-vous à deux mètres, face à la caméra. La projection est une simulation visuelle locale, vos images ne quittent pas cet appareil.</p><div className="scan-preview">{active ? <><video ref={videoRef} autoPlay playsInline /><div className="scan-guide" /></> : photo ? <img src={photo} alt="Silhouette scannée" /> : <div className="scan-placeholder"><UserRound size={34} /><span>Cadrez votre silhouette entière</span></div>}</div><div className="camera-actions">{active ? <button className="primary-button" onClick={capture}><Check size={16} /> Capturer ma silhouette</button> : <button className="primary-button" onClick={startScan}><Camera size={16} /> {photo ? 'Reprendre le scan' : 'Démarrer le scan'}</button>}{photo && <button className="secondary-button" onClick={() => onComplete(photo)}>Utiliser ce scan</button>}</div></div></div>
}

function ItemCard({ item, onFavorite, unavailable, onToggleUnavailable }) { return <article className={unavailable ? 'item-card item-unavailable' : 'item-card'}><div className="item-image-wrap"><img src={item.image} alt={item.name} /><button className="favorite-button" onClick={() => onFavorite(item.id)} aria-label="Ajouter aux favoris"><Heart size={16} fill={item.favorite ? 'currentColor' : 'none'} /></button>{unavailable && <span className="unavailable-badge">Au lavage</span>}</div><div className="item-info"><h3>{item.name}</h3><span>{item.category}</span><b>{item.style}</b></div>{onToggleUnavailable && <button className="laundry-toggle" onClick={() => onToggleUnavailable(item.id)}><WashingMachine size={13} /> {unavailable ? 'Rendre disponible' : 'Mettre au lavage'}</button>}</article> }

function OutfitStudio({ items, onScan, scanPhoto }) {
  const [selected, setSelected] = useState({ Hauts: 1, Bas: 2, Chaussures: 4, Accessoires: 5 }); const [saved, setSaved] = useState(false); const groups = ['Hauts', 'Bas', 'Chaussures', 'Accessoires']; const currentItems = groups.map((group) => items.find((item) => item.id === selected[group])).filter(Boolean)
  return <div className="page animate-in"><section className="page-heading"><div><span className="eyebrow">Projection de silhouette</span><h1>Essayage 3D</h1><p className="intro">Composez une tenue complète, accessoires compris.</p></div><button className="primary-button" onClick={onScan}><Camera size={17} /> Scanner mon corps</button></section><div className="studio-layout"><div className="body-stage">{scanPhoto ? <img className="scanned-body" src={scanPhoto} alt="Votre silhouette scannée" /> : <><div className="stage-grid" /><div className="body-silhouette"><span className="silhouette-head" /><span className="silhouette-body" /></div></>}<div className="projected-pieces">{currentItems.map((item) => <img src={item.image} alt="" key={item.id} />)}</div><div className="projection-copy"><Sparkles size={16} /><span>{scanPhoto ? 'Tenue projetée sur votre scan' : `${currentItems.length} pièces projetées`}</span></div></div><div className="outfit-controls"><div className="studio-title"><div><span className="eyebrow">Tenue active</span><h2>Power dressing minimal</h2></div><Heart size={17} /></div>{groups.map((group) => <label className="slot" key={group}><span>{group}</span><select value={selected[group]} onChange={(event) => { setSaved(false); setSelected((current) => ({ ...current, [group]: Number(event.target.value) })) }}>{items.filter((item) => item.category === group).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label>)}<button className="primary-button full-width" onClick={() => setSaved(true)}><Check size={16} /> {saved ? 'Tenue enregistrée' : 'Enregistrer cette tenue'}</button></div></div><div className="simulation-note"><Camera size={17} /><div><strong>Projection personnalisée</strong><p>Scannez votre silhouette pour remplacer le mannequin par votre image et visualiser les volumes de la tenue.</p></div></div></div>
}

export default function App() {
  const [activeTab, setActiveTab] = useState('home'); const [items, setItems] = useState(initialItems); const [unavailableIds, setUnavailableIds] = useState([]); const [search, setSearch] = useState(''); const [category, setCategory] = useState('Tous'); const [showModal, setShowModal] = useState(false); const [showScan, setShowScan] = useState(false); const [scanPhoto, setScanPhoto] = useState(''); const [saved, setSaved] = useState(true); const [favoriteLooks, setFavoriteLooks] = useState([1]); const [planner, setPlanner] = useState({ '2026-09-25': 1 }); const [selectedDate, setSelectedDate] = useState('2026-09-25'); const [selectedPlannerLook, setSelectedPlannerLook] = useState(1)
  const filteredItems = useMemo(() => items.filter((item) => `${item.name} ${item.category} ${item.style}`.toLowerCase().includes(search.toLowerCase()) && (category === 'Tous' || item.category === category)), [items, search, category]); const selectedPlan = looks.find((look) => look.id === planner[selectedDate])
  function goToSearch(event) { if (event.key === 'Enter' && search.trim()) setActiveTab('wardrobe') }; function addItem(newItem) { setItems((current) => [{ ...newItem, id: Date.now(), style: 'Nouveau', favorite: false }, ...current]); setShowModal(false); setActiveTab('wardrobe') }; function toggleFavorite(id) { setItems((current) => current.map((item) => item.id === id ? { ...item, favorite: !item.favorite } : item)) }; function toggleFavoriteLook(id) { setFavoriteLooks((current) => current.includes(id) ? current.filter((lookId) => lookId !== id) : [...current, id]) }; function toggleUnavailable(id) { setUnavailableIds((current) => current.includes(id) ? current.filter((itemId) => itemId !== id) : [...current, id]) }; function savePlannerLook() { setPlanner((current) => ({ ...current, [selectedDate]: selectedPlannerLook })) }
  return <div className="app-shell"><aside className="sidebar"><div><div className="brand"><span className="brand-mark">A</span><div><strong>AL STUDIO</strong><small>Garde-robe intelligente</small></div></div><div className="profile-mini"><div className="avatar">CL</div><div><strong>Bonjour, Clara</strong><span>Marseille, France</span></div><ChevronRight size={15} /></div><nav>{navigation.map(({ id, label, icon: Icon }) => <button key={id} className={activeTab === id ? 'nav-item active' : 'nav-item'} onClick={() => setActiveTab(id)}><Icon size={18} />{label}</button>)}</nav></div><div className="sidebar-bottom"><button className="nav-item"><CircleUserRound size={18} />Mon profil</button><span className="version">AL Studio · 2.4</span></div></aside><main className="main-content"><header className="topbar"><div className="mobile-brand">AL / STUDIO</div><div className="topbar-actions"><label className="global-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={goToSearch} placeholder="Rechercher" /></label><button className="avatar avatar-small">CL</button></div></header>
    {activeTab === 'home' && <div className="page animate-in"><section className="welcome-row"><div><span className="eyebrow">Vendredi 25 septembre 2026</span><h1>Votre style, en mouvement.</h1><p className="intro">Les pièces qui font la différence aujourd'hui.</p></div><div className="weather"><SunMedium size={23} /><div><strong>21°</strong><span>Marseille · doux et clair</span></div><CloudSun size={20} className="weather-cloud" /></div></section><section className="hero-look"><div className="hero-copy"><span className="pill"><Sparkles size={13} /> Recommandation du jour</span><h2>Power dressing<br /><em>minimal</em></h2><p>Une silhouette précise et confortable pour passer de la réunion au dîner sans changer de rythme.</p><div className="beauty-line"><span>Beauté</span><span>Chignon bas lissé · Nude glow</span></div><div className="hero-actions"><button className="light-button" onClick={() => setActiveTab('studio')}>Essayer le look <ArrowUpRight size={16} /></button><button className={saved ? 'save-button saved' : 'save-button'} onClick={() => { setSaved(!saved); toggleFavoriteLook(1) }} aria-label="Sauvegarder le look"><Heart size={17} fill={saved ? 'currentColor' : 'none'} /></button></div></div><div className="hero-image"><img src={looks[0].image} alt="Silhouette power dressing minimal" /><span className="image-label">01 / 03</span></div></section><section className="section-block"><div className="section-heading"><div><span className="eyebrow">Sélection personnelle</span><h2>Pièces clés</h2></div><button className="text-button" onClick={() => setActiveTab('wardrobe')}>Tout le dressing <ArrowUpRight size={15} /></button></div><div className="item-grid">{items.slice(0, 4).map((item) => <ItemCard key={item.id} item={item} onFavorite={toggleFavorite} unavailable={unavailableIds.includes(item.id)} onToggleUnavailable={toggleUnavailable} />)}</div></section></div>}
    {activeTab === 'wardrobe' && <div className="page animate-in"><section className="page-heading"><div><span className="eyebrow">Votre collection</span><h1>Mon dressing</h1><p className="intro">{items.length} pièces, prêtes à être combinées.</p></div><button className="primary-button" onClick={() => setShowModal(true)}><Plus size={17} /> Ajouter une pièce</button></section><div className="toolbar"><div className="search-box"><Search size={16} /><input placeholder="Rechercher une pièce, catégorie ou style" value={search} onChange={(event) => setSearch(event.target.value)} /></div><div className="filters">{['Tous', 'Hauts', 'Bas', 'Robes', 'Manteaux', 'Chaussures', 'Accessoires'].map((option) => <button className={category === option ? 'filter active' : 'filter'} key={option} onClick={() => setCategory(option)}>{option}</button>)}</div></div>{filteredItems.length ? <div className="wardrobe-grid">{filteredItems.map((item) => <ItemCard key={item.id} item={item} onFavorite={toggleFavorite} unavailable={unavailableIds.includes(item.id)} onToggleUnavailable={toggleUnavailable} />)}</div> : <div className="empty-state"><Search size={27} /><h2>Aucune pièce trouvée</h2><p>Essayez un autre nom, style ou catégorie.</p></div>}</div>}
    {activeTab === 'laundry' && <div className="page animate-in"><section className="page-heading"><div><span className="eyebrow">Disponibilité du dressing</span><h1>Au lavage</h1><p className="intro">Indiquez les pièces temporairement indisponibles.</p></div><div className="stat-chip"><WashingMachine size={16} /><strong>{unavailableIds.length}</strong><span>pièce{unavailableIds.length > 1 ? 's' : ''} au lavage</span></div></section>{unavailableIds.length ? <div className="wardrobe-grid">{items.filter((item) => unavailableIds.includes(item.id)).map((item) => <ItemCard key={item.id} item={item} onFavorite={toggleFavorite} unavailable onToggleUnavailable={toggleUnavailable} />)}</div> : <div className="empty-state"><WashingMachine size={28} /><h2>Tout est disponible</h2><p>Aucune pièce n'est actuellement au lavage.</p><button className="primary-button" onClick={() => setActiveTab('wardrobe')}><Shirt size={16} /> Voir mon dressing</button></div>}</div>}
    {activeTab === 'studio' && <OutfitStudio items={items} onScan={() => setShowScan(true)} scanPhoto={scanPhoto} />}
    {activeTab === 'hairstyles' && <div className="page animate-in"><section className="page-heading"><div><span className="eyebrow">Mise en beauté</span><h1>Suggestions coiffures</h1><p className="intro">Des idées pensées pour accompagner vos silhouettes.</p></div><div className="stat-chip"><Sparkles size={16} /><strong>03</strong><span>looks beauté</span></div></section><div className="look-grid hairstyle-grid">{hairstyles.map((style) => <article className="look-card" key={style.id}><div className="look-image"><img src={style.image} alt={style.title} /><span>{style.tag}</span></div><div className="look-meta"><div><h2>{style.title}</h2><p>{style.note}</p></div><button className="icon-button"><ArrowUpRight size={17} /></button></div></article>)}</div></div>}
    {activeTab === 'favorites' && <div className="page animate-in"><section className="page-heading"><div><span className="eyebrow">Votre sélection</span><h1>Tenues favorites</h1><p className="intro">Les silhouettes que vous aimez retrouver.</p></div><div className="stat-chip"><Heart size={16} /><strong>{favoriteLooks.length}</strong><span>looks sauvegardés</span></div></section>{favoriteLooks.length ? <div className="look-grid">{looks.filter((look) => favoriteLooks.includes(look.id)).map((look) => <article className="look-card" key={look.id}><div className="look-image"><img src={look.image} alt={look.title} /><button className="favorite-button" onClick={() => toggleFavoriteLook(look.id)} aria-label="Retirer des favoris"><Heart size={16} fill="currentColor" /></button><span>{look.tag}</span></div><div className="look-meta"><div><h2>{look.title}</h2><p>{look.note}</p></div><button className="icon-button" onClick={() => setActiveTab('studio')}><ArrowUpRight size={17} /></button></div></article>)}</div> : <div className="empty-state"><Heart size={27} /><h2>Votre sélection est vide</h2><p>Appuyez sur le cœur d'un look pour le retrouver ici.</p><button className="primary-button" onClick={() => setActiveTab('discover')}>Explorer les inspirations</button></div>}</div>}
    {activeTab === 'discover' && <div className="page animate-in"><section className="page-heading"><div><span className="eyebrow">Éditorial AL</span><h1>Inspirations</h1><p className="intro">Des idées qui commencent dans votre dressing.</p></div><div className="stat-chip"><Sparkles size={16} /><strong>12</strong><span>looks disponibles</span></div></section><div className="look-grid">{looks.map((look) => <article className="look-card" key={look.id}><div className="look-image"><img src={look.image} alt={look.title} /><button className="favorite-button" onClick={() => toggleFavoriteLook(look.id)} aria-label="Ajouter aux favoris"><Heart size={16} fill={favoriteLooks.includes(look.id) ? 'currentColor' : 'none'} /></button><span>{look.tag}</span></div><div className="look-meta"><div><h2>{look.title}</h2><p>{look.note}</p></div><button className="icon-button" onClick={() => setActiveTab('studio')}><ArrowUpRight size={17} /></button></div></article>)}</div></div>}
    {activeTab === 'calendar' && <div className="page animate-in"><section className="page-heading"><div><span className="eyebrow">Organiser sa semaine</span><h1>Planning des looks</h1><p className="intro">Sélectionnez une date pour créer et enregistrer une tenue.</p></div></section><div className="calendar-panel"><div className="calendar-header"><button className="icon-button">‹</button><strong>Septembre 2026</strong><button className="icon-button">›</button></div><div className="week-labels">{['Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam', 'Dim'].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({ length: 30 }, (_, index) => { const date = `2026-09-${String(index + 1).padStart(2, '0')}`; return <button className={selectedDate === date ? 'day selected' : 'day'} key={date} onClick={() => { setSelectedDate(date); if (planner[date]) setSelectedPlannerLook(planner[date]) }}><span>{index + 1}</span>{planner[date] && <Check size={13} />}</button> })}</div><div className="planner-editor"><span className="eyebrow">Date sélectionnée · {selectedDate}</span><h3>Créer une tenue pour ce jour</h3><div className="planner-row"><select value={selectedPlannerLook} onChange={(event) => setSelectedPlannerLook(Number(event.target.value))}>{looks.map((look) => <option value={look.id} key={look.id}>{look.title}</option>)}</select><button className="primary-button" onClick={savePlannerLook}><Check size={16} /> Enregistrer</button></div></div>{selectedPlan && <div className="planned-look"><img src={selectedPlan.image} alt="Look planifié" /><div><span className="eyebrow">Tenue enregistrée le {selectedDate}</span><h3>{selectedPlan.title}</h3><p>{selectedPlan.note}</p></div><ArrowUpRight size={18} /></div>}</div></div>}
  </main><nav className="mobile-nav">{navigation.map(({ id, label, icon: Icon }) => <button key={id} className={activeTab === id ? 'active' : ''} onClick={() => setActiveTab(id)}><Icon size={18} /><span>{label}</span></button>)}</nav>{showModal && <AddItemModal onClose={() => setShowModal(false)} onAdd={addItem} />}{showScan && <BodyScan onClose={() => setShowScan(false)} onComplete={(photo) => { setScanPhoto(photo); setShowScan(false) }} />}</div>
}